pipeline {
    agent any

    stages {
        stage('Unit Tests - BackEnd') {
            agent {
                docker {
                    image 'golang:tip-trixie'
                    reuseNode true
                    args '-e GOCACHE=/tmp/.cache -e GOMODCACHE=/tmp/.modcache'
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go install github.com/jstemmer/go-junit-report/v2@latest'
                    sh 'go test ./... -v 2>&1 | go-junit-report > report.xml'
                }
            }
            post { 
                always{
                    junit 'bugtracker-backend/report.xml'
                }
            }
        }

        stage('Unit Tests - FrontEnd') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
            post { 
                always{
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}
