pipeline {
    agent any

    stages {
        stage('Unit Tests - Back End') {
            agent {
                docker {
                    image 'golang:tip-trixie'
                    reuseNode true
                }
            }
            steps {
                 dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
