pipeline {
    agent any

    stages {
        stage('Unit Tests - BackEnd') {
            agent {
                docker {
                    image 'golang:tip-trixie'
                    reuseNode true
                    args '-e GOCACHE=/tmp/.cache -e GOMODCACHE=/tmp/.modcache'
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        # 1. Instalar go-junit-report
                        go install github.com/jstemmer/go-junit-report/v2@latest

                        # 2. Agregar el bin de Go al PATH para poder usar la herramienta instalada
                        export PATH=$PATH:$(go env GOPATH)/bin

                        # 3. Correr tests y generar reporte JUnit
                        # Nota: 2>&1 redirige errores al output estándar para que la herramienta lo lea
                        go test -v ./... 2>&1 | go-junit-report > test-results.xml

                        # 4. Generar Reporte de Cobertura (CORREGIDO)
                        # Quitamos el '-o' y agregamos el guion a -covermode
                        go test -coverprofile=coverage.out -covermode=atomic ./...
                        
                        # 5. Convertir a HTML
                        go tool cover -html=coverage.out -o coverage.html

                        # 6. Mover reporte
                        mkdir -p reports
                        mv coverage.html reports/
                    '''
                }
            }
            post { 
                    // Publish Test Results and Coverage Report to Jenkins
                always{
                    junit 'bugtracker-backend/test-results.xml'
                    publishHTML(target: [
                        reportDir: 'bugtracker-backend/reports',
                        reportFiles: 'coverage.html',
                        reportName: 'Backend Coverage Report'
                    ])
                }
            }
        }

        stage('Unit Tests - FrontEnd') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
            post { 
                always{
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}
